[font]
size = 18
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold" }
italic = { family = "0xProto Nerd Font", style = "Regular Italic" }
bold_italic = { family = "0xProto Nerd Font", style = "Bold Italic" }

[window]
dimensions = { columns = 120, lines = 35 }
padding = { x = 5, y = 5 }
opacity = 0.99
